### ISSUE TITLE
Views - Query Seriazlier

### ISSUE THREAD

**Issue by axeldelaguardia** [TooLong-DidntRead/tldr_api#16]
views.py
After query_serializer.is_valid(), can we just call query_serializer.save() instead of creating a new Query and then saving?

**Comment by Elle-M** [comment]
According to ChatGBT: 

Yes, you can directly call query_serializer.save() instead of creating a new Query instance and then saving it separately. The save() method of the serializer handles both creating a new instance and saving it to the database.

Here's the updated code snippet:

```
if query_serializer.is_valid():
    query = query_serializer.save()
    result = Result(response=QueryGPT.initiate_query(query), query=query)
    result.save()
    serializer = ResultSerializer(result, many=False)
    return Response(serializer.data, status=status.HTTP_201_CREATED)
else:
    return Response(query_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
```
By calling query_serializer.save(), the validated data will be used to create a new Query object and save it to the database. This approach simplifies the code by combining the creation and saving steps into a single method call.

**Comment by axeldelaguardia** [comment]
Closing issue as this was solved in a previous commit.
